app = "telegram-bot-123"  

primary_region = "fra"  # تختار أقرب سيرفر لك (fra = فرانكفورت)

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
